filegroup(
    name = "license_files",
    srcs = [
        "checkstyle-file-mpl-header.txt",
        "checkstyle-file-apache-header.txt",
        "checkstyle-file-commercial-header.txt",
        "checkstyle-file-mpl-fulltext.txt",
        "checkstyle-file-apache-fulltext.txt",
        "checkstyle-file-commercial-fulltext.txt",
    ],
    visibility = ["//visibility:public"]
)
