py_binary(
    name = "unused_deps",
    srcs = ["unused_deps.py"],
    data = [
        "@unused_deps_mac//file",
        "@unused_deps_linux//file",
        "@buildozer_mac//file",
        "@buildozer_linux//file",
    ]
)
